site_name: Live de Python

theme: readthedocs

# MkDocs Bootstrap
# theme: yeti
# theme: amelia

# MkDocs Material
# theme: 
#   name: material

repo_url: https://github.com/python-marcus-mariano/Tutorial-documentation-with-mkdocs-live-91/tree/master

nav:
  - Home: index.md
  - Sobre: sobre.md
  - Contribuições:
    - Tradução: contribuir/traducao.md
    - Eventos: contribuir/eventos.md

extra_css:
  - css/extra_css.css
